name: Build binaries

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths-ignore:
      - '**.md'
      - '.devcontainer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
      - '.github/**/*.md'
      - '.vscode/**'
      - 'HBC/**'
      - 'Languages/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.devcontainer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
      - '.github/**/*.md'
      - '.vscode/**'
      - 'HBC/**'
      - 'Languages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:20250527
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"

      - name: Compile USB Loader GX
        run: make release -j2

      - name: Package
        if: ${{ vars.ALLOW_UPLOADS == 'true' }}
        run: |
          mkdir -p upload/apps/usbloader_gx
          cp boot.dol upload/apps/usbloader_gx
          cp HBC/icon.png upload/apps/usbloader_gx
          cp HBC/meta.xml upload/apps/usbloader_gx
          echo "sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Upload binary
        if: ${{ vars.ALLOW_UPLOADS == 'true' }}
        uses: actions/upload-artifact@v4
        with: 
          name: usbloadergx_${{ env.sha }}
          path: upload

      - name: Upload debug binary
        if: ${{ vars.ALLOW_UPLOADS == 'true' }}
        uses: actions/upload-artifact@v4
        with: 
          name: usbloadergx_${{ env.sha }}_debug
          path: boot.elf
